### ISSUE TITLE
2019.11.1 aiorun version breaks aiologfields

### ISSUE THREAD

**Issue by wallies** [cjrh/aiorun#32]
New version of aiorun breaks aiologfields, in that no log fields declared by aiologfields log anymore after updating aiorun. Nothing is logging outside of aiologfields or aiorun to say anything is wrong as well

**Comment by cjrh** [comment]
I suspect this was the change that broke it: https://github.com/cjrh/aiorun/commit/ba73ee6d4ade7465a5daba4e287c234c5727228c#diff-d49eeefc6a3217eb36fe8864ea8139c7R175

So we use a new loop instance for `aiorun.run()` for each run, unless a loop instance was passed in.  The easiest way to fix this is to make sure you call `aiologfields.install()` _inside the context of `aiorun.run()`_; this will allow aiologfields to use the correct loop instance.  I would expect the custom task factory application to still work, but I guess it would need to be tested.

To properly fix the issue, in aiologfields we should probably either:
- require `.install()` to take a loop parameter, e.g. `aiologfields.install(loop)`; pretty explicit, but upstream Python wants to move away from seeing "loop" anywhere in programs so...
- make `aiologfields.install()` a coroutine so that you are forced to call it inside the context of a running loop (thus allowing it to know the correct loop on which to change the task factory).

Would it be weird to make `install()` a coroutine merely to force it being called within the context of a running loop (it wouldn't perform any IO at all)?

**Comment by cjrh** [comment]
@wallies I've started working on this in https://github.com/cjrh/aiologfields/pull/9

The change is that `aiologfields.install` will be required to receive a loop parameter.  To make this work with `aiorun`, you either have to create your own loop (and pass it to `aiorun.run()` as well as `aiologfields.install()`), or you have to call `install()` inside the context of a coroutine:

```
import aiorun
import aiologfields

async def main():
    loop = asyncio.get_running_loop()
    aiologfields.install(loop)
    <etc>
 
aiorun.run(main()
```

With this second option described above, there is an important caveat: since `install()` is called _within the context of an existing task_, that task will not have been produced by the replacement factory used inside aiologfields; that means the extra logging stuff won't have been applied inside that task. I'm still thinking about a solution for this.

**Comment by wallies** [comment]
For the moment we moved aiologfields.install() inside the context of aiorun.run() and it works but I suspect this will make it work alot better, so will await this fix

**Comment by cjrh** [comment]
Ok. Since you already have a workaround implemented, and I have a separate tracking PR in the other repo, I'm closing this.
