### ISSUE TITLE
Event loop shouldn't be stopped when the exception handler is invoked with no exception

### ISSUE THREAD

**Issue by sersorrel** [cjrh/aiorun#56]
Since #43, the event loop will be stopped whenever its exception handler is invoked, whether or not the context contains an `exception` key. But the exception handler can be invoked by anything with access to the event loop, and at least one third-party library invokes it without passing `exception`, namely [aiohttp](https://github.com/aio-libs/aiohttp/blob/a8d9ec3f1667463e80545b1cacc7833d1ff305e9/aiohttp/client_reqrep.py#L751):

```python
            if self._loop.get_debug():
                _warnings.warn(
                    f"Unclosed response {self!r}", ResourceWarning, source=self
                )
                context = {"client_response": self, "message": "Unclosed response"}
                if self._source_traceback:
                    context["source_traceback"] = self._source_traceback
                self._loop.call_exception_handler(context)
```

Since this is just a warning, it feels like aiorun should not stop the loop when this happens. (Arguably aiohttp is at fault here for invoking the exception handler for an unexceptional event, but imo aiorun should deal with it gracefully anyway.)

If you agree, I can PR a fix for this?

**Comment by cjrh** [comment]
Hi @sersorrel!

Thanks for the report. I have also read the report over at aiohttp, and will post a comment there also.  I have these thoughts:

1. There is an escape hatch in aiorun: you can supply your own exception handler and deal with these any way you like. Search in the README for the phrase _It is also possible to configure your exception handler on the loop_. In that scenario the `stop_on_unhandled_errors` parameter is no longer necessary (or allowed) because your own supplied handler has complete control.  Based on how you present this report, and the one at aiohttp, this is probably the best option for your use-case.

2. You can use `stop_on_unhandled_errors=False`, as recommended on the issue at aiohttp. FWIW I personally always use this because I never want the loop to stop without explicitly asking for that.  But I know many other people have different requirements that are not my requirements.

3. IIUC, this problem only happens when the loop has debug=True.  So (for aiohttp) the problem can also be removed by setting debug=False.

4. On the aiohttp issue, the maintainer is correct that we should be pedantic about ensuring resources are properly closed. I agree strongly with this. If you make sure that this happens, the warning problem goes away. The example you gave in the other report, about how Python doesn't complain if you fail to call `.close()` on a file is really great example of why this is important. The practice of not explicitly closing file handles causes real problems for other Python implementations that are not CPython, and I'm thinking in particular of PyPy. PyPy does not use simple reference counting to dispose of things like file handles and these can be kept alive long after the identifiers go out of scope. That is why it is so important to make sure one uses context managers for file access in Python - to ensure that file handles are closed after use (so that your code will also work properly on other Python implementations).

My conclusion is that I don't think you should make a PR to change the existing behaviour in aiorun for this.  Hopefully the escape hatch in (1) will work for your use-case.

Would you ok for me to close this issue?

**Comment by sersorrel** [comment]
That all makes sense, thanks. Yep, I'm fine with this being closed.

One thing: if there's no `exception` in the context, then you get the "Unhandled exception; stopping loop." log message, and everything shuts down, but you don't get any indication of what actually went wrong unless you happen to realise that the ResourceWarning from aiohttp is what caused the shutdown. Would you consider logging at least the `message`, or even just the entire context, in the exception handler? it might also be nice to pass `exc_info=pending_exception_to_raise` to the logger call, so that even if another exception is raised during shutdown (which happens consistently for me, I am yet to work out what I'm doing wrong) you still see what the original error was.

**Comment by cjrh** [comment]
Good point, I agree the situation where no exception is provided should be handled better. I'd accept a PR including the message in the logger message. For the other point about `exc_info`, do Python's (version 3+) chained exceptions not automatically do this?

**Comment by cjrh** [comment]
Oops, yeah I realise now this context is one in which there is no underlying exception, so nothing to chain.  

Ok you convinced me, if you make a PR let's also add the `exc_info` to the logger call.
