### ISSUE TITLE
`loop` in run function has wrong docstring

### ISSUE THREAD

**Issue by prchristie** [cjrh/aiorun#74]
Currently it says

```
    :param loop: Optionally supply your own loop. If missing, the
        default loop attached to the current thread context will
        be used, i.e., whatever ``asyncio.get_event_loop()`` returns.
```

Indicating the use of `asyncio.get_event_loop()`, but 

```python
    loop_was_supplied = bool(loop)

    if not loop_was_supplied:
        if use_uvloop:
            import uvloop

            asyncio.set_event_loop_policy(uvloop.EventLoopPolicy())
        else:
            asyncio.set_event_loop_policy(asyncio.DefaultEventLoopPolicy())

        loop = asyncio.new_event_loop()
        asyncio.set_event_loop(loop)
```

Shows that we use `asyncio.new_event_loop()`

This will cause certain programs that use `Tasks` to stop working when plugging in aiorun until they provide the loop that is actually being used, and there is no easily found documentation to understand why a program has stopped working. 

My opinion is to actually use `asyncio.get_event_loop()`, but I admit that I may not completely understand the benefits to using `asyncio.new_event_loop()` so a warning or indicator may be more appropriate.

**Comment by cjrh** [comment]
> This will cause certain programs that use Tasks to stop working when plugging in aiorun until they provide the loop that is actually being used, and there is no easily found documentation to understand why a program has stopped working.

On this point, `aiorun.run`, like stdlib `asyncio.run`, is intended to be the starting point for async execution, and tasks should really be getting created inside an async context already, when a loop is already active.  This is how `asyncio.create_task` actually works: it uses `get_running_loop` to get the loop instance internally, which only works from inside the context of a running loop.  So my feeling here is that there is nothing that requires changing.

**Comment by prchristie** [comment]
Seems like a fair resolution to me :) 

To shed more light on this issue for someone with less asyncio knowledge that may be hitting this issue as I know it took me a LONG time to understand generally, if you have code like the following that creates tasks on an event loop created by you:

```python
import asyncio
import aiorun

class Program:
    def __init__(self, loop):
        self.loop = loop

    def start(self):
        self.loop.create_task(self.my_async_fn())

    async def my_async_fn(self):
        await asyncio.sleep(1)
        print("I have just completed!")


loop = asyncio.get_event_loop()
my_program = Program(loop)
my_program.start()
aiorun.run()
```

you will find that `I have just completed!` is never printed, and pressing cntl+c produces something like `RuntimeWarning: coroutine 'Program.my_async_fn' was never awaited`. This is because async code can only execute on a single event loop per thread, IE multiple event loops will block each other. As we started `my_async_fn` on the event loop we made and did not provide the loop we used to `aiorun.run()`, a new event loop was made internally using `loop = asyncio.new_event_loop()` and `loop.run_forever()` was called on that event loop, not ours. Note that `run_forever()` is one of the event loop functions that blocks other event loops. Thus, control was never passed to our event loop to schedule the created task and the task was never awaited.

The solution is pretty simple, we want to control which event loop controls execution, so we just provide a loop to the `run` function: `aiorun.run(loop=asyncio.get_event_loop()) # the event loop you want aiorun to use`

**Comment by cjrh** [comment]
@prchristie Thank you for your detailed notes and providing code samples. It makes it much easier to help.

Generally speaking, for users of asyncio, and libraries like aiorun and similar, you really want to stay away from `get_event_loop()` as much as possible. It can only hurt you.  The one you want to use is [get_running_loop](https://docs.python.org/3/library/asyncio-eventloop.html?highlight=get_running_loop#asyncio.get_running_loop) which was introduced in Python 3.7.  The bit that makes it safer is this (from the linked docs):

> If there is no running event loop a [RuntimeError](https://docs.python.org/3/library/exceptions.html#RuntimeError) is raised. **This function can only be called from a coroutine** or a callback.

Because you can only call `get_running_loop` from inside an async context (it will `RuntimeError` if you don't), there is no ambiguity: you always get the "correct" loop instance back.

Rewriting your first example:

```python
import asyncio
import aiorun

class Program:
    async def start(self):
        loop = asyncio.get_running_loop()
        self.task = loop.create_task(self.my_async_fn())

    async def my_async_fn(self):
        await asyncio.sleep(1)
        print("I have just completed!")

aiorun.run(my_program.start())
```

because you never need to actually store the `loop` instance. You can obtain it at any time from `get_running_loop()`, as long as that is called while the loop is running.

Because the idiom of `get_running_loop()` followed by `loop.create_task` is so common, there is a shortcut provided in [asyncio.create_task](https://docs.python.org/3/library/asyncio-task.html?highlight=create_task#asyncio.create_task) which does those two things for you.  So you could shorten it slightly to this:

```python
import asyncio
import aiorun

class Program:
    async def start(self):
        self.task = asyncio.create_task(self.my_async_fn())

    async def my_async_fn(self):
        await asyncio.sleep(1)
        print("I have just completed!")

aiorun.run(my_program.start())
```

In this version, there is no mention of a `loop` anywhere, and this is exactly what you want. In my experience any manual fiddling with loops results in regret.

Hope that helps. I've made a PR to fix the docstring and I added a warning high up in the README about how new loops are automatically created.
