### ISSUE TITLE
programatically stopping a loop

### ISSUE THREAD

**Issue by catchthemonster** [cjrh/aiorun#76]
Hi, great library, thanks a lot...
Documentation is good too! My issue is following:
I do want to start two separate rest api services via corutines in async way. I have no issues setting up a handler to catch exceptions in event_loop.
however I want to be able programmatically to stop the loop.
anything after run(loop=loop) is not going to work!
what is the way to actually stop the loop and consequently stop two rest api verticals....

Regards,

**Comment by cjrh** [comment]
It depends most strongly on the REST servers you're using. Each of the frameworks (aiohttp, fastapi, sanic, etc.) will have a slightly different way of shutting down. You will have to study the docs of your chosen framework to see how they want you to start up and shut down their server. Usually they (the frameworks) control the starting up and shutting down of the event loop, so aiorun probably can't help much here.

**Comment by cjrh** [comment]
> however I want to be able programmatically to stop the loop.
anything after run(loop=loop) is not going to work!

To answer this question from the perspective of aiorun, all you have to do is call `asyncio.get_running_loop().stop()`.  This will initiate the shutdown process, which means the sequence of steps listed in the README such as task cancellation, waiting for all tasks to finish, shutting down the executor etc. Whether or not this works for the specific web frameworks you're using is more a matter for those frameworks.

It sounds like you've got a solution using processes and process termination, which I agree is a pretty clean way to do it since you will also have memory space isolation between the different services.

**Comment by catchthemonster** [comment]
Yes, I agree.
